# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='history.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rhistory.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n\tTimeScope\x12.\n\nstart_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xc2\x01\n%GetHistoryDataObjectRecordSetsRequest\x12!\n\x19history_data_object_names\x18\x01 \x03(\t\x12\x15\n\rdata_versions\x18\x02 \x03(\x05\x12\x0f\n\x07\x66ilters\x18\x03 \x03(\t\x12\x1f\n\x0btime_scopes\x18\x04 \x03(\x0b\x32\n.TimeScope\x12-\n\x0etime_relations\x18\x05 \x03(\x0e\x32\x15.EnumDataTimeRelation*R\n\x14\x45numDataTimeRelation\x12\x10\n\x0c\x44\x41TA_DEFAULT\x10\x00\x12\x13\n\x0f\x44\x41TA_RELATION_1\x10\x01\x12\x13\n\x0f\x44\x41TA_RELATION_2\x10\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_ENUMDATATIMERELATION = _descriptor.EnumDescriptor(
  name='EnumDataTimeRelation',
  full_name='EnumDataTimeRelation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATA_DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_RELATION_1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_RELATION_2', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=354,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_ENUMDATATIMERELATION)

EnumDataTimeRelation = enum_type_wrapper.EnumTypeWrapper(_ENUMDATATIMERELATION)
DATA_DEFAULT = 0
DATA_RELATION_1 = 1
DATA_RELATION_2 = 2



_TIMESCOPE = _descriptor.Descriptor(
  name='TimeScope',
  full_name='TimeScope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='TimeScope.start_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='TimeScope.end_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=155,
)


_GETHISTORYDATAOBJECTRECORDSETSREQUEST = _descriptor.Descriptor(
  name='GetHistoryDataObjectRecordSetsRequest',
  full_name='GetHistoryDataObjectRecordSetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='history_data_object_names', full_name='GetHistoryDataObjectRecordSetsRequest.history_data_object_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_versions', full_name='GetHistoryDataObjectRecordSetsRequest.data_versions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filters', full_name='GetHistoryDataObjectRecordSetsRequest.filters', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_scopes', full_name='GetHistoryDataObjectRecordSetsRequest.time_scopes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_relations', full_name='GetHistoryDataObjectRecordSetsRequest.time_relations', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=352,
)

_TIMESCOPE.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TIMESCOPE.fields_by_name['end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETHISTORYDATAOBJECTRECORDSETSREQUEST.fields_by_name['time_scopes'].message_type = _TIMESCOPE
_GETHISTORYDATAOBJECTRECORDSETSREQUEST.fields_by_name['time_relations'].enum_type = _ENUMDATATIMERELATION
DESCRIPTOR.message_types_by_name['TimeScope'] = _TIMESCOPE
DESCRIPTOR.message_types_by_name['GetHistoryDataObjectRecordSetsRequest'] = _GETHISTORYDATAOBJECTRECORDSETSREQUEST
DESCRIPTOR.enum_types_by_name['EnumDataTimeRelation'] = _ENUMDATATIMERELATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeScope = _reflection.GeneratedProtocolMessageType('TimeScope', (_message.Message,), dict(
  DESCRIPTOR = _TIMESCOPE,
  __module__ = 'history_pb2'
  # @@protoc_insertion_point(class_scope:TimeScope)
  ))
_sym_db.RegisterMessage(TimeScope)

GetHistoryDataObjectRecordSetsRequest = _reflection.GeneratedProtocolMessageType('GetHistoryDataObjectRecordSetsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETHISTORYDATAOBJECTRECORDSETSREQUEST,
  __module__ = 'history_pb2'
  # @@protoc_insertion_point(class_scope:GetHistoryDataObjectRecordSetsRequest)
  ))
_sym_db.RegisterMessage(GetHistoryDataObjectRecordSetsRequest)


# @@protoc_insertion_point(module_scope)
